--RN_01
CREATE OR REPLACE TRIGGER HORAS_EMPLEADOS
BEFORE INSERT OR UPDATE ON ESTADISTICAS
FOR EACH ROW
DECLARE
W_DNI VARCHAR2(9);
BEGIN
SELECT DNI INTO W_DNI FROM JUGADORES WHERE DNI = :NEW.DNI;
IF :NEW.HORASTRABAJADAS <40 AND :NEW.DNI = W_DNI
    THEN raise_application_error(-20600, ' Cada jugador debe trabajar más de 40 horas. Ha trabajado: ' || :NEW.HORASTRABAJADAS);
    ELSE
     DBMS_OUTPUT.put_line ('El jugador ha cumplido las horas mínimas, ha trabajado: '|| :NEW.HORASTRABAJADAS || ' horas');
END IF;
END;
/
--RN_02
CREATE OR REPLACE TRIGGER COBRO_PREMIO
BEFORE UPDATE ON LIGAS
FOR EACH ROW
BEGIN
IF :NEW.FECHACOBROPREMIO is NULL
    THEN raise_application_error(-20603, ' No se puede modificar los datos de las ligas hasta que se cobre el premio.');
END IF;
END;
/
--RN_03 
CREATE OR REPLACE TRIGGER EQUIPOS_FORTNITE
BEFORE INSERT ON SEENFRENTAEN
FOR EACH ROW
DECLARE
CONTADOR INTEGER;
CONTADOR2 INTEGER;
SUMA INTEGER;
BEGIN

SELECT COUNT(OID_ER) INTO CONTADOR FROM SEENFRENTAEN NATURAL JOIN PARTIDOS WHERE VIDEOJUEGO='FORTNITE';
SELECT COUNT(OID_EQ) INTO CONTADOR2 FROM JUEGA NATURAL JOIN PARTIDOS WHERE VIDEOJUEGO='FORTNITE';
SUMA := CONTADOR+CONTADOR2;
IF SUMA>=99
THEN raise_application_error(-20611, :NEW.OID_ER || ' No pueden jugar más de 100 equipos de Fortnite un partido.');   
END IF;
END;
/
CREATE OR REPLACE TRIGGER EQUIPOS_FORTNITE2
BEFORE INSERT ON JUEGA
FOR EACH ROW
DECLARE
CONTADOR INTEGER;
CONTADOR2 INTEGER;
SUMA INTEGER;
BEGIN

SELECT COUNT(OID_ER) INTO CONTADOR FROM SEENFRENTAEN NATURAL JOIN PARTIDOS WHERE VIDEOJUEGO='FORTNITE';
SELECT COUNT(OID_EQ) INTO CONTADOR2 FROM JUEGA NATURAL JOIN PARTIDOS WHERE VIDEOJUEGO='FORTNITE';
SUMA := CONTADOR+CONTADOR2;
IF SUMA>=99
THEN raise_application_error(-20601, :NEW.OID_EQ || ' No pueden jugar más de 100 equipos de Fortnite un partido.');   
END IF;
END;
/
CREATE OR REPLACE TRIGGER EQUIPOS
BEFORE INSERT ON JUEGA
FOR EACH ROW
DECLARE
cont INTEGER;
BEGIN
SELECT COUNT(*) INTO cont FROM juega NATURAL JOIN PARTIDOS WHERE VIDEOJUEGO !='Fortnite' AND OID_PT = :NEW.OID_PT;
DBMS_OUTPUT.put_line('Trigger: ' || cont);
IF cont>=1
THEN raise_application_error(-20622, ' No pueden jugar 2 o más equipos enemigos en un partido.');   
END IF;
END;
/
CREATE OR REPLACE TRIGGER EQUIPOS_RIVALES
BEFORE INSERT ON SEENFRENTAEN
FOR EACH ROW
DECLARE
cont INTEGER;
BEGIN
SELECT COUNT(*) INTO cont FROM seEnfrentaEn NATURAL JOIN PARTIDOS WHERE VIDEOJUEGO !='FORTNITE' AND OID_PT = :NEW.OID_PT;
IF cont>=1
THEN raise_application_error(-20602, :NEW.OID_ER || ' No pueden jugar 2 o más equipos aliados en un partido.');   
END IF;
END;
/
--RN_04
CREATE OR REPLACE TRIGGER EMPLEADOS_DATOSGUARDADOS
BEFORE INSERT ON EMPLEADOS
FOR EACH ROW
DECLARE
WDNI CHAR(9);
BEGIN
DELETE FROM EMPLEADOS WHERE DNI = :NEW.DNI;
END;
/
